apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-new
    role: server
    deployment: platsrv-registry-api
  name: platsrv-registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-new
      role: api
      deployment: platsrv-registry-api
  template:
    metadata:
      labels:
        app: registry-new
        role: api
        deployment: platsrv-registry-api
    spec:
      containers:
        - name: platsrv-registry-api
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongoURL
                  name: new-registry-api
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: authSecret
                  name: new-registry-api
            - name: AUTH_RELM
              value: devhub
            - name: AUTH_SERVER_URL
              value: https://oidc.gov.bc.ca/auth
            - name: AUTH_RESOURCE
              value: registry-api
            - name: NATS_HOST
              value: nats://nats.platform-provisioner.svc
            - name: NATS_PORT
              value: '4222'
            - name: NATS_SUBJECT
              value: registry_project_provisioning_klab
            - name: NATS_SKIP
              value: 'true'
            - name: CHES_TOKEN_URL
              value: https://oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token
            - name: CHES_CLIENT_ID
              value: PS_REG_SERVICE_CLIENT
            - name: CHES_API_URL
              value: https://ches-dev.apps.silver.devops.gov.bc.ca/api/v1/
            - name: CHES_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: chesClientSecret
                  name: new-registry-api
          # image: image-registry.openshift-image-registry.svc:5000/platform-registry-tools/registry-api-new-api:1.0.2
          image: platsrv-registry-api-main-build
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /api/ehlo
          #     port: 5000
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 6000
          #   successThreshold: 1
          #   timeoutSeconds: 3
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 92Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 2
