kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: platsrv-registry-api
  annotations:
    openshift.io/host.generated: "true"
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: platsrv-registry-api
spec:
  host: https://registry.developer.gov.bc.ca/
  to:
    kind: Service
    name: platsrv-registry-api
    weight: 100
  port:
    targetPort: 4000-tcp
  tls:
    termination: edge
  wildcardPolicy: None
