version: "3.7"
x-env: &defaults
  NODE_ENV: development
  MONGODB_USERNAME: 
  MONGODB_PASSWORD:
  MONGODB_HOST: registry-mongo
  MONGODB_NAME:
  AUTH_RELM:
  AUTH_SERVER_URL:
  AUTH_RESOURCE:
  AUTH_SECRET:
  NATS_HOST:
  NATS_PORT:
  NATS_SUBJECT:
  NATS_SKIP:
  CHES_TOKEN_URL:
  CHES_CLIENT_ID:
  CHES_CLIENT_SECRET:
  CHES_API_URL:
services:
  mongo:
    container_name: registry-mongo
    image: registry/db
    build:
      context: db/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./mongo_data
        target: /data/db
      - type: bind
        source: ./db
        target: /opt/db
    ports:
      - 27017:27017
    environment: *defaults
  api:
    container_name: registry-api-new
    image: registry-api-new/api
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /opt/app
    #   # - type: tmpfs
    #   #   target: /tmp
    #   #   tmpfs:
    #   #     size: 128000000
    ports:
      - 4000:4000

    environment:
      <<: *defaults
      PORT: 4000
    # command: >
    #   bash -c "sleep 5 && npm run start"
    # command: >
    #   bash -c "sleep 5 && npm run dev:docker"
