version: "3.7"
x-env: &defaults
  NODE_ENV: development
  MONGODB_USERNAME: admin
  MONGODB_PASSWORD: admin_pw
  MONGODB_NAME: registry
  MONGO_INITDB_DATABASE:
  AUTH_RELM:
  AUTH_SERVER_URL:
  AUTH_RESOURCE:
  AUTH_SECRET:
  NATS_HOST:
  NATS_PORT:
  NATS_SUBJECT:
  NATS_SKIP:
  CHES_TOKEN_URL:
  CHES_CLIENT_ID:
  CHES_CLIENT_SECRET:
  CHES_API_URL:
  DATABASE_URL: mongodb://admin:admin_pw@mongo1:27017/registry?retryWrites=true&w=majority&directConnection=true
  MONGODB_REPLICA_COUNT: 2
  MONGODB_REPLICA_NAME: registry-rc
services:
  mongo1:
    container_name: mongo1
    image: registry/db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./mongo_data/rc1
        target: /data/db
      - type: bind
        source: ./db
        target: /opt/db
    ports:
      - 27017:27017
    depends_on:
      - mongo2
    links:
      - mongo2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    environment: *defaults
  mongo2:
    container_name: mongo2
    image: registry/db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./mongo_data/rc2
        target: /data/db
      - type: bind
        source: ./db
        target: /opt/db
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    environment: *defaults
  api:
    container_name: registry-api-new
    image: registry-api-new/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      <<: *defaults
      PORT: 4000



