name: api_Test_Happy_Path

on:
  workflow_dispatch:

env:
        URL: 'https://dev.loginproxy.gov.bc.ca/auth/realms/platform-services/protocol/openid-connect/token'


#permissions:
  #id-token: write # This is required for requesting the JWT
  #contents: read  # This is required for actions/checkout        

jobs:
  happy_path_test:
    name: Runs the Happy Path suite of tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install latest nodejs  
        uses: actions/setup-node@v3
        with:
          check-latest: true

      - name: Display the node version    
        run: node --version      
      
      - name: Install newman    
        run: npm install -g newman
      
      - name: Display newman version
        run: newman --version
          
      - name: Run the test
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd apiTest
          pwd
          newman run testHappyPath.postman_collection.json --environment ./apiTest/TestEnv.postman_environment.json
         
         
   #   - name: Zip Results folder
   #     run: |
   #         cd proofOfConcept
   #         zip -r snapshotResults.zip ./results
   #         ls -la
            
   #   - name: Upload Zipped results folder to artifacts
   #     uses: actions/upload-artifact@v3
   #     with:
   #       name: snapshotResults
   #       path: ./proofOfConcept/snapshotResults.zip
    