name: api_Test_Suite_1    #The test suite reports failures, but the test suite 
                          #itself succeed. You need to read the produced report to
                          # check if verify if the individual tests have succeeded or failed

on:
  workflow_dispatch:
    
jobs:
  happy_path_test:
    name: Runs the Happy Path suite of tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install latest nodejs  
        uses: actions/setup-node@v3
        with:
          check-latest: true

      - name: Display the node version    
        run: node --version      
      
      - name: Install newman    
        run: npm install -g newman
      
      - name: Display newman version
        run: newman --version
          
      - name: Run the test
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd apiTest
          pwd
          newman run testHappyPath.postman_collection.json --env-var auth-url=${{ secrets.AUTH_URL }} --env-var api-url=${{secrets.API_URL}} --env-var auth_email=${{secrets.AUTH_EMAIL}} --env-var auth_pwd=${{secrets.AUTH_PWD}} > resultHappyApiTest.txt
         
      - name: Upload results  to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resultHappyApiTest.txt
          path: ./apiTest/resultHappyApiTest.txt

  unhappy_path_test:
    name: Runs the Unhappy Path suite of tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install latest nodejs  
        uses: actions/setup-node@v3
        with:
          check-latest: true

      - name: Display the node version    
        run: node --version      
      
      - name: Install newman    
        run: npm install -g newman
      
      - name: Display newman version
        run: newman --version
          
      - name: Run the test
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd apiTest
          pwd
          newman run testUnhappyPath.postman_collection.json --env-var api-url=${{secrets.API_URL}} > resultUnhappyApiTest.txt
               
      - name: Upload results  to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resultUnhappyApiTest.txt
          path: ./apiTest/resultUnhappyApiTest.txt
       