name: api_Test_Happy_Path2 #it requires an env variables file, that would expose the variables values.
                           # I have saved this workflow simply to show another way to run a postman collection in GHA
on:
  workflow_dispatch:

jobs:
  happy_path_test:
    name: Runs the Happy Path suite of tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: calling newman VM
        uses: matt-ball/newman-action@master
        with:
          collection: ./apiTest/testHappyPath.postman_collection.json
          environment: ./apiTest/TestEnv.postman_environment.json
          reporters: '["cli"]'
  