name: api_Test_Happy_Path

on:
  workflow_dispatch:
    
jobs:
  happy_path_test:
    name: Runs the Happy Path suite of tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: install latest nodejs  
        uses: actions/setup-node@v3
        with:
          check-latest: true

      - name: Display the node version    
        run: node --version      
      
      - name: Install newman    
        run: npm install -g newman
      
      - name: Display newman version
        run: newman --version
          
      - name: Run the test
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd apiTest
          pwd
          newman run testHappyPath.postman_collection.json --env-var auth-url=${{ secrets.AUTH_URL }} --env-var api-url=${{secrets.API_URL}} --env-var auth_email=${{secrets.AUTH_EMAIL}} --env-var auth_pwd=${{secrets.AUTH_PWD}} > resultApiTest.txt
         
      - name: Upload results  to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resultApiTest.txt
          path: ./apiTest/resultApiTest.txt

      - name: Fail test if results include Failure
        continue-on-error: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd apiTest
          myString=`cat resultApiTest.txt | grep failure`
          len=`expr "$myString"`                                  

          if [[ $len -gt 0 ]]
          then
          exit 1
          fi



        echo ${#myString}    